[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'cache_forge'
optimizer_runs = 1000000
via-ir = true
gas_reports = ["Escrow", "EscrowFactory"]

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

[fmt]
bracket_spacing = true
multiline_func_header = 'params_first'
wrap_comments = true
