[profile.default]
ffi = true
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
optimizer_runs = 1000000
via-ir = true
evm_version = 'shanghai'
solc_version = '0.8.23'
gas_reports = ["EscrowSrc", "EscrowDst", "EscrowFactory", "MerkleStorageInvalidator"]
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # store source code in the json file directly
remappings = [
    "@1inch/limit-order-protocol-contract/=/Users/george/Workspace/tokamak-contracts/lib/limit-order-protocol/",
    "@1inch/limit-order-settlement/=/Users/george/Workspace/tokamak-contracts/lib/limit-order-settlement/",
    "@1inch/solidity-utils/=/Users/george/Workspace/tokamak-contracts/lib/solidity-utils/",
    "solidity-utils/=/Users/george/Workspace/tokamak-contracts/lib/solidity-utils/",
    "limit-order-protocol/=/Users/george/Workspace/tokamak-contracts/lib/limit-order-protocol/",
    "limit-order-settlement/=/Users/george/Workspace/tokamak-contracts/lib/limit-order-settlement/",
    "@openzeppelin/contracts/=/Users/george/Workspace/tokamak-contracts/lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=/Users/george/Workspace/tokamak-contracts/lib/chainlink-brownie-contracts/contracts/",
    "@gnosis.pm/safe-contracts/=/Users/george/Workspace/tokamak-contracts/lib/safe-contracts/",
    "ds-test/=/Users/george/Workspace/tokamak-contracts/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=/Users/george/Workspace/tokamak-contracts/lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=/Users/george/Workspace/tokamak-contracts/lib/forge-std/src/",
    "murky/=/Users/george/Workspace/tokamak-contracts/lib/murky/",
    "openzeppelin-contracts/=/Users/george/Workspace/tokamak-contracts/lib/openzeppelin-contracts/"
]
fs_permissions = [
    { access = "read", path = "./examples/config/config.json" },
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    {access = "read-write", path = "./" },
]

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

[fmt]
line_length = 120
bracket_spacing = true
multiline_func_header = 'params_first'
wrap_comments = true

[fuzz]
runs = 1024

[profile.zksync]
src = 'contracts'
libs = ['lib']
fallback_oz = true
is_system = false
mode = "3"

[rpc_endpoints]
monad_testnet = "${MONAD_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

# Configure verifiers for different chains
[etherscan]
# For Monad Testnet (Sourcify)
monad_testnet = { key = "DUMMY_KEY", url = "https://sourcify-api-monad.blockvision.org", chain = 10143 }

# For Sepolia (Etherscan)
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
